---
lcd:
  url: https://terra-classic-lcd.publicnode.com
  get_timeout_in_seconds: 30
  nb_of_attempts_if_failure: 5
  nb_minutes_of_break_between_attempts: 5
bdd:
  host_name: xxxxxxxx.xxx
  db_name: xxx
  user_name: xxx
  password: xxx
  port: 3306
  tbl_TotalSupplies_name: tblTotalSupplies3
  tbl_NbStakedLunc_name: tblNbStakedLunc
  tbl_CommunityPoolContent_name: tblCommunityPoolContent
email:
  host_name: xxxxxxxx.xxx
  smtp_port: 465
  from: xxxxxxxx@xxxxxxxx.xxx
  pwd: xxx
  to: xxxxxxxx@xxxxxxxx.xxx